import React from "react";
import "./__contactMe.css";
import useSpline from "@splinetool/r3f-spline";
import { OrthographicCamera } from "@react-three/drei";
import Spline from "@splinetool/react-spline";
const ContactMe = () => {
  return (
    <div
      data-scroll-section
      className="main-cotainner-Contact-me"
      style={{ height: "150vh" }}
    >
      <div className="troid-model">
        {/* <Canvas shadows flat linear>
          <Scene />
          <OrbitControls />
        </Canvas> */}
        <Spline scene="https://prod.spline.design/eH2rvPhFgaadeC1g/scene.splinecode" />
      </div>
      <div className="claMessageExamle"></div>
    </div>
  );
};

export default ContactMe;

/*
  Auto-generated by Spline
*/
